### ISSUE TITLE
Checklist for use in rust-analyzer/rowan

### ISSUE THREAD

**Issue by CAD97** [CAD97/sorbus#60]
- [ ] Work on stable (Rust 1.46.0)
- [ ] Migrate repository from cad97/sorbus to rust-analyer/sorbus (cc @matklad)
- [X] Initial port of rowan to use sorbus (https://github.com/rust-analyzer/rowan/pull/69)
  - [ ] Merge sorbus use into rowan
- [ ] Initial port of r-a to use rowan on sorbus
  - [ ] Merge r-a use of rowan on sorbus
- [ ] Performance and memory use tests
- [ ] ... ?
- [ ] Profit

and improvements to r-a possible after it uses sorbus:

- [ ] Share green cache between files
  - [ ] Implicit cache sharing in Rowan? Needs experimentation.
  - [ ] GC cache when unloading files
- [ ] Utilize cheaper `SyntaxPtr`
